services:
  db:
    image: postgres:18
    restart: always
    shm_size: 128mb
    ports: 
    - "5435:5432"
    environment:
      POSTGRES_PASSWORD: example
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080