/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["AppController_getHello"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["UsersController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["UsersController_read"];
    put: operations["UsersController_update"];
    post?: never;
    delete: operations["UsersController_delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/networks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Создать новую сеть */
    post: operations["NetworksController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/networks/{network_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Получить сеть по ID */
    get: operations["NetworksController_get"];
    /** Обновить сеть по ID */
    put: operations["NetworksController_update"];
    post?: never;
    /** Удалить сеть по ID */
    delete: operations["NetworksController_delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/networks/{network_id}/devices": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Создать новое устройство */
    post: operations["DevicesController_createDevice"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/networks/{network_id}/devices/{device_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Получить устройство по ID */
    get: operations["DevicesController_getDevice"];
    /** Обновить устройство по ID */
    put: operations["DevicesController_updateDevice"];
    post?: never;
    /** Удалить устройство по ID */
    delete: operations["DevicesController_deleteDevice"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/network/{network_id}/tags": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Создать новый тег */
    post: operations["TagsController_createTag"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/network/{network_id}/tags/{tag_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Получить тег по ID */
    get: operations["TagsController_getTag"];
    /** Обновить тег по ID */
    put: operations["TagsController_updateTag"];
    post?: never;
    /** Удалить тег по ID */
    delete: operations["TagsController_deleteTag"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/networks/{network_id}/rules": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Создать новое правило */
    post: operations["RulesController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/networks/{network_id}/rules/{rule_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Получить правило по ID */
    get: operations["RulesController_get"];
    /** Обновить правило по ID */
    put: operations["RulesController_update"];
    post?: never;
    /** Удалить правило по ID */
    delete: operations["RulesController_delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Network: {
      /**
       * @description UUID сети (генерируется автоматически при создании)
       * @example a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11
       */
      id?: string;
      /**
       * @description Название VPN сети
       * @example Office Network
       */
      name: string;
      /**
       * @description Описание сети
       * @example Main office VPN network
       */
      description: string;
      /**
       * @description IP адрес сети
       * @example 192.168.1.0
       */
      ip: string;
      /**
       * @description Размер подсети (CIDR)
       * @example 24
       */
      subnet: number;
      /**
       * @description Содержимое конфигурационного файла (.conf)
       * @example proto udp
       *     port 1194
       *     ...
       */
      config: string;
      /**
       * @description UUID администратора, создавшего сеть
       * @example a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11
       */
      adminId: string;
    };
    Device: {
      /**
       * @description UUID устройства (генерируется автоматически при создании)
       * @example a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11
       */
      id?: string;
      /**
       * @description Название устройства
       * @example Office-PC-01
       */
      name: string;
      /**
       * @description IP адрес устройства в сети
       * @example 192.168.1.10
       */
      ip: string;
      /**
       * @description Содержимое конфигурационного файла устройства (.conf)
       * @example client
       *     remote vpn.example.com 1194
       *     ...
       */
      config: string;
      /**
       * @description UUID сети, к которой подключается устройство
       * @example a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11
       */
      network_id: string;
    };
    Tag: {
      /**
       * @description Название тега
       * @example Office
       */
      name: string;
      /**
       * @description UUID сети
       * @example a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11
       */
      network_id: string;
    };
    Rule: {
      /**
       * @description ID тега устройства отправителя
       * @example a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11
       */
      source: string;
      /**
       * @description ID тега устройства получатеся
       * @example a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11
       */
      dest: string;
      /**
       * @description Протокол (При отсутсвтии прямого указания протокола, применяется ко всем(ANY))
       * @example TCP
       */
      protocol: string;
      /**
       * @description Порт (При отсутсвтии прямого указания порта, применяется ко всем(ALL)
       * @example 443
       */
      port: number;
      /**
       * @description UUID сети, к которой относится правило
       * @example a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11
       */
      network_id: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AppController_getHello: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_read: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  NetworksController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Network"];
      };
    };
    responses: {
      /** @description Сеть успешно создана */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  NetworksController_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description UUID сети */
        network_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Сеть найдена */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Network"];
        };
      };
      /** @description Сеть не найдена */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  NetworksController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description UUID сети */
        network_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Network"];
      };
    };
    responses: {
      /** @description Сеть успешно обновлена */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Сеть не найдена */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  NetworksController_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description UUID сети */
        network_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Сеть успешно удалена */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Сеть не найдена */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  DevicesController_createDevice: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description UUID сети */
        network_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Device"];
      };
    };
    responses: {
      /** @description Устройство успешно создано */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  DevicesController_getDevice: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description UUID устройства */
        device_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Устройство найдено */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Device"];
        };
      };
      /** @description Устройство не найдено */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  DevicesController_updateDevice: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description UUID устройства */
        device_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Device"];
      };
    };
    responses: {
      /** @description Устройство успешно обновлено */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Устройство не найдено */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  DevicesController_deleteDevice: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description UUID устройства */
        device_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Устройство успешно удалено */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Устройство не найдено */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TagsController_createTag: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description UUID сети */
        network_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Tag"];
      };
    };
    responses: {
      /** @description Тег успешно создан */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TagsController_getTag: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description UUID тега */
        tag_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Тег найден */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Tag"];
        };
      };
      /** @description Тег не найден */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TagsController_updateTag: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description UUID тега */
        tag_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Tag"];
      };
    };
    responses: {
      /** @description Тег успешно обновлён */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Тег не найден */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TagsController_deleteTag: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description UUID тега */
        tag_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Тег успешно удалён */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Тег не найден */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RulesController_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description UUID сети */
        network_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Rule"];
      };
    };
    responses: {
      /** @description Правило успешно создано */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RulesController_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description UUID правила */
        rule_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Правило найдено */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Rule"];
        };
      };
      /** @description Правило не найдено */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RulesController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description UUID правила */
        rule_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Rule"];
      };
    };
    responses: {
      /** @description Правило успешно обновлено */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Правило не найдено */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RulesController_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description UUID правила */
        rule_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Правило успешно удалено */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Правило не найдено */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
