/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/networks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить сети, в которых состоит пользователь */
        get: operations["NetworksController_getMyNetworks"];
        put?: never;
        /** Создать новую сеть */
        post: operations["NetworksController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/networks/{network_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить сеть по ID */
        get: operations["NetworksController_get"];
        /** Обновить сеть по ID */
        put: operations["NetworksController_update"];
        /** Войти в сеть */
        post: operations["NetworksController_enter"];
        /** Удалить сеть по ID */
        delete: operations["NetworksController_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/networks/{network_id}/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить устройства по фильтрам */
        get: operations["DevicesController_getDevicesWithFilters"];
        put?: never;
        /** Создать новое устройство */
        post: operations["DevicesController_createDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/networks/{network_id}/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить устройство по ID */
        get: operations["DevicesController_getDevice"];
        /** Обновить устройство по ID */
        put: operations["DevicesController_updateDevice"];
        post?: never;
        /** Удалить устройство по ID */
        delete: operations["DevicesController_deleteDevice"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/networks/{network_id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить теги сети */
        get: operations["TagsController_getAllTags"];
        put?: never;
        /** Создать новый тег */
        post: operations["TagsController_createTag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/networks/{network_id}/tags/{tag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить тег по ID */
        get: operations["TagsController_getTag"];
        /** Обновить тег по ID */
        put: operations["TagsController_updateTag"];
        post?: never;
        /** Удалить тег по ID */
        delete: operations["TagsController_deleteTag"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/networks/{network_id}/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить правила сети */
        get: operations["RulesController_getAllRules"];
        put?: never;
        /** Создать новое правило */
        post: operations["RulesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/networks/{network_id}/rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить правило по ID */
        get: operations["RulesController_get"];
        /** Обновить правило по ID */
        put: operations["RulesController_update"];
        post?: never;
        /** Удалить правило по ID */
        delete: operations["RulesController_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateNetworkDto: {
            /** @description The name of the network */
            name: string;
            /** @description A description of the network */
            description: string;
            /**
             * Format: cidrv4
             * @description The IP address range of the network
             */
            cidr: string;
        };
        NetworkDto: {
            /**
             * Format: uuid
             * @description The unique identifier of the network
             */
            id: string;
            /** @description The name of the network */
            name: string;
            /** @description A description of the network */
            description: string;
            /**
             * Format: cidrv4
             * @description The IP address range of the network
             */
            cidr: string;
        };
        NetworkEnterCredentialsDto: {
            /** @description The network access key */
            key: string;
        };
        UpdateNetworkDto: {
            /** @description The name of the network */
            name?: string;
            /** @description A description of the network */
            description?: string;
            /**
             * Format: cidrv4
             * @description The IP address range of the network
             */
            cidr?: string;
        };
        CreateDeviceDto: {
            /** @description The name of the device */
            name: string;
            /**
             * Format: ipv4
             * @description The IP address of the device
             */
            ip: string;
            /** @description The identifier of the device owner */
            ownerId?: string;
        };
        DeviceDto: {
            /**
             * Format: uuid
             * @description The unique identifier of the device
             */
            id: string;
            /** @description The name of the device */
            name: string;
            /**
             * Format: ipv4
             * @description The IP address of the device
             */
            ip: string;
            /** @description The identifier of the device owner */
            ownerId: string;
        };
        UpdateDeviceDto: {
            /** @description The name of the device */
            name?: string;
            /**
             * Format: ipv4
             * @description The IP address of the device
             */
            ip?: string;
            /** @description The identifier of the device owner */
            ownerId?: string;
        };
        CreateTagDto: {
            /** @description The name of the tag */
            name: string;
            /**
             * @description The display color of the tag
             * @enum {string}
             */
            color: "red" | "blue" | "green" | "yellow" | "purple" | "orange";
        };
        TagDto: {
            /**
             * Format: uuid
             * @description The unique identifier of the tag
             */
            id: string;
            /** @description The name of the tag */
            name: string;
            /**
             * @description The display color of the tag
             * @enum {string}
             */
            color: "red" | "blue" | "green" | "yellow" | "purple" | "orange";
        };
        UpdateTagDto: {
            /** @description The name of the tag */
            name?: string;
            /**
             * @description The display color of the tag
             * @enum {string}
             */
            color?: "red" | "blue" | "green" | "yellow" | "purple" | "orange";
        };
        CreateRuleDto: {
            /**
             * Format: uuid
             * @description The source tag identifier
             */
            source?: string;
            /**
             * Format: uuid
             * @description The destination tag identifier
             */
            dest?: string;
            /** @description The network protocol */
            protocol?: string;
            /** @description The destination port */
            port?: number;
        };
        RuleDto: {
            /**
             * Format: uuid
             * @description The unique identifier of the rule
             */
            id: string;
            /**
             * Format: uuid
             * @description The source tag identifier
             */
            source?: string;
            /**
             * Format: uuid
             * @description The destination tag identifier
             */
            dest?: string;
            /** @description The network protocol */
            protocol?: string;
            /** @description The destination port */
            port?: number;
        };
        UpdateRuleDto: {
            /**
             * Format: uuid
             * @description The source tag identifier
             */
            source?: string;
            /**
             * Format: uuid
             * @description The destination tag identifier
             */
            dest?: string;
            /** @description The network protocol */
            protocol?: string;
            /** @description The destination port */
            port?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NetworksController_getMyNetworks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID сети */
                network_id: unknown;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Сети получены */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetworkDto"][];
                };
            };
        };
    };
    NetworksController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNetworkDto"];
            };
        };
        responses: {
            /** @description Сеть успешно создана */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NetworksController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID сети */
                network_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Сеть найдена */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetworkDto"];
                };
            };
            /** @description Сеть не найдена */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NetworksController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID сети */
                network_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNetworkDto"];
            };
        };
        responses: {
            /** @description Сеть успешно обновлена */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Сеть не найдена */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NetworksController_enter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID сети */
                network_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NetworkEnterCredentialsDto"];
            };
        };
        responses: {
            /** @description Успешный вход */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Сеть не найдена */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NetworksController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID сети */
                network_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Сеть успешно удалена */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Сеть не найдена */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DevicesController_getDevicesWithFilters: {
        parameters: {
            query?: {
                /** @description Пойсковой запрос по названию */
                q?: string;
                /** @description Названия тэгов, повешенных на устройство */
                tags?: string;
                /** @description UUID владельца устройства */
                owner_id?: string;
            };
            header?: never;
            path: {
                network_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Устройства найдены */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceDto"][];
                };
            };
            /** @description Устройства не найдены */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DevicesController_createDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                network_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDeviceDto"];
            };
        };
        responses: {
            /** @description Устройство успешно создано */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DevicesController_getDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID устройства */
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Устройство найдено */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceDto"];
                };
            };
            /** @description Устройство не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DevicesController_updateDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID устройства */
                device_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDeviceDto"];
            };
        };
        responses: {
            /** @description Устройство успешно обновлено */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Устройство не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DevicesController_deleteDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID устройства */
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Устройство успешно удалено */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Устройство не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TagsController_getAllTags: {
        parameters: {
            query?: {
                /** @description Пойсковой запрос по названию */
                q?: string;
            };
            header?: never;
            path: {
                network_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Теги получены */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagDto"][];
                };
            };
        };
    };
    TagsController_createTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID сети */
                network_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTagDto"];
            };
        };
        responses: {
            /** @description Тег успешно создан */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TagsController_getTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID тега */
                tag_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Тег найден */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagDto"];
                };
            };
            /** @description Тег не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TagsController_updateTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID тега */
                tag_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTagDto"];
            };
        };
        responses: {
            /** @description Тег успешно обновлён */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Тег не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TagsController_deleteTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID тега */
                tag_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Тег успешно удалён */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Тег не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RulesController_getAllRules: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                network_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Правила получены */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleDto"][];
                };
            };
        };
    };
    RulesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                network_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRuleDto"];
            };
        };
        responses: {
            /** @description Правило успешно создано */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RulesController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID правила */
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Правило найдено */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleDto"];
                };
            };
            /** @description Правило не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RulesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID правила */
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRuleDto"];
            };
        };
        responses: {
            /** @description Правило успешно обновлено */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Правило не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RulesController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID правила */
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Правило успешно удалено */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Правило не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
