/**
 * This file is auto-generated by nestjs-proto-gen-ts
 */

import type { Metadata } from "@grpc/grpc-js";
import type { Observable } from "rxjs";

export namespace controlplane {
  export interface RouterControlPlane {
    // Called by a router at startup to fetch the full desired network and peer state.
    getRouterConfiguration(
      data: GetRouterConfigurationRequest,
      metadata?: Metadata,
      ...rest: any[]
    ): Observable<RouterConfiguration>;
    // Opened by a router after startup to receive live configuration snapshots.
    watchRouterConfiguration(
      data: WatchRouterConfigurationRequest,
      metadata?: Metadata,
      ...rest: any[]
    ): Observable<RouterConfigurationUpdate>;
    // Opened by a router to report WireGuard handshake and connection activity.
    reportRouterEvents(
      data: Observable<RouterEvent>,
      metadata?: Metadata,
      ...rest: any[]
    ): Observable<ReportRouterEventsResponse>;
  }
  export interface RouterInfo {
    routerId?: string;
    hostname?: string;
    version?: string;
    supportedProtocols?: string[];
    labels?: { [key: string]: string };
  }
  export interface GetRouterConfigurationRequest {
    router?: controlplane.RouterInfo;
    currentRevision?: string;
  }
  export interface WatchRouterConfigurationRequest {
    router?: controlplane.RouterInfo;
    currentRevision?: string;
  }
  export interface RouterConfiguration {
    // Opaque backend revision. Routers echo it on later requests and watches.
    revision?: string;
    networks?: controlplane.NetworkConfig[];
    protocols?: controlplane.ProtocolInstanceConfig[];
  }
  export interface NetworkConfig {
    id?: string;
    name?: string;
    cidr?: string;
    serverAddress?: string;
    mtu?: number;
    statusPort?: number;
    peers?: controlplane.PeerConfig[];
  }
  export interface PeerConfig {
    id?: string;
    networkId?: string;
    name?: string;
    address?: string;
    allowedIps?: string[];
    labels?: { [key: string]: string };
    wireguard?: controlplane.WireGuardPeerConfig;
  }
  export interface WireGuardPeerConfig {
    // Raw 32-byte WireGuard public key.
    publicKey?: Uint8Array;
    // Raw 32-byte WireGuard preshared key, when enabled.
    presharedKey?: Uint8Array;
  }
  export interface ProtocolInstanceConfig {
    id?: string;
    name?: string;
    instanceName?: string;
    networkId?: string;
    listenPort?: number;
    publicHost?: string;
    // Empty means all peers in the referenced network are eligible for this instance.
    peerIds?: string[];
    wireguard?: controlplane.WireGuardProtocolConfig;
  }
  export interface WireGuardProtocolConfig {
    // Raw 32-byte WireGuard interface private key used by the router.
    interfacePrivateKey?: Uint8Array;
    // Raw 32-byte WireGuard interface public key advertised to peers.
    interfacePublicKey?: Uint8Array;
    persistentKeepaliveSeconds?: number;
  }
  export interface RouterConfigurationUpdate {
    revision?: string;
    reason?: controlplane.ConfigurationUpdateReason;
    configuration?: controlplane.RouterConfiguration;
    changedResources?: controlplane.ChangedResource[];
  }
  export enum ConfigurationUpdateReason {
    CONFIGURATION_UPDATE_REASON_UNSPECIFIED = 0,
    CONFIGURATION_UPDATE_REASON_INITIAL_SNAPSHOT = 1,
    CONFIGURATION_UPDATE_REASON_MANUAL_REFRESH = 2,
    CONFIGURATION_UPDATE_REASON_NETWORK_CHANGED = 3,
    CONFIGURATION_UPDATE_REASON_PEER_CHANGED = 4,
    CONFIGURATION_UPDATE_REASON_PROTOCOL_CHANGED = 5,
  }
  export interface ChangedResource {
    type?: controlplane.ChangedResourceType;
    id?: string;
    networkId?: string;
    operation?: controlplane.ChangeOperation;
  }
  export enum ChangedResourceType {
    CHANGED_RESOURCE_TYPE_UNSPECIFIED = 0,
    CHANGED_RESOURCE_TYPE_NETWORK = 1,
    CHANGED_RESOURCE_TYPE_PEER = 2,
    CHANGED_RESOURCE_TYPE_PROTOCOL_INSTANCE = 3,
  }
  export enum ChangeOperation {
    CHANGE_OPERATION_UNSPECIFIED = 0,
    CHANGE_OPERATION_CREATED = 1,
    CHANGE_OPERATION_UPDATED = 2,
    CHANGE_OPERATION_DELETED = 3,
  }
  export interface RouterEvent {
    router?: controlplane.RouterInfo;
    eventId?: string;
    configurationRevision?: string;
    observedAt?: google.protobuf.Timestamp;
    wireguardHandshake?: controlplane.WireGuardHandshakeLog;
    wireguardConnection?: controlplane.WireGuardConnectionLog;
    wireguardPacket?: controlplane.WireGuardPacketObservation;
  }
  export interface WireGuardHandshakeLog {
    networkId?: string;
    protocolInstanceId?: string;
    protocolInstanceName?: string;
    peerId?: string;
    endpoint?: string;
    stage?: controlplane.WireGuardHandshakeStage;
    senderIndex?: number;
    receiverIndex?: number;
    packetSize?: number;
  }
  export enum WireGuardHandshakeStage {
    WIRE_GUARD_HANDSHAKE_STAGE_UNSPECIFIED = 0,
    WIRE_GUARD_HANDSHAKE_STAGE_INITIATION = 1,
    WIRE_GUARD_HANDSHAKE_STAGE_RESPONSE = 2,
    WIRE_GUARD_HANDSHAKE_STAGE_COOKIE_REPLY = 3,
  }
  export interface WireGuardConnectionLog {
    networkId?: string;
    protocolInstanceId?: string;
    protocolInstanceName?: string;
    peerId?: string;
    endpoint?: string;
    state?: controlplane.PeerConnectionState;
    latestHandshakeAt?: google.protobuf.Timestamp;
    rxBytes?: number;
    txBytes?: number;
  }
  export enum PeerConnectionState {
    PEER_CONNECTION_STATE_UNSPECIFIED = 0,
    PEER_CONNECTION_STATE_CONNECTED = 1,
    PEER_CONNECTION_STATE_DISCONNECTED = 2,
  }
  export interface WireGuardPacketObservation {
    networkId?: string;
    protocolInstanceId?: string;
    protocolInstanceName?: string;
    peerId?: string;
    endpoint?: string;
    packetType?: controlplane.WireGuardPacketType;
    backend?: string;
    senderIndex?: number;
    receiverIndex?: number;
    packetSize?: number;
    packetsSeen?: number;
  }
  export enum WireGuardPacketType {
    WIRE_GUARD_PACKET_TYPE_UNSPECIFIED = 0,
    WIRE_GUARD_PACKET_TYPE_HANDSHAKE_INITIATION = 1,
    WIRE_GUARD_PACKET_TYPE_HANDSHAKE_RESPONSE = 2,
    WIRE_GUARD_PACKET_TYPE_COOKIE_REPLY = 3,
    WIRE_GUARD_PACKET_TYPE_TRANSPORT = 4,
    WIRE_GUARD_PACKET_TYPE_UNKNOWN = 5,
  }
  export interface ReportRouterEventsResponse {
    acceptedEvents?: number;
    lastEventId?: string;
  }
}
export namespace google {
  export namespace protobuf {
    export interface Timestamp {
      seconds?: number;
      nanos?: number;
    }
  }
}
